/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project3_1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fariha
 */
public class addModel extends javax.swing.JFrame {

    /**
     * Creates new form addModel
     */
    String m_username = "m";
    int back = 0;

    public addModel() {
        initComponents();
        jLabel1.setText(m_username);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("select * from model");
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.setRowCount(0);
            while (rs.next()) {

                String mName = rs.getString("md_name");
                String enName = rs.getString("en_name");
                String mType = rs.getString("md_type");

                String data[] = {mName, enName, mType, Float.toString(rs.getFloat("t_f_amount"))};

                tm.addRow(data);

            }
            rs = st.executeQuery("select en_name from engine");
            while (rs.next()) {
                String enname = rs.getString("en_name");
                jComboBox1.addItem(enname);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public addModel(String x, int y) {
        initComponents();
        m_username = x;
        back = y;
        jLabel1.setText(m_username);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("select * from model");
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.setRowCount(0);
            while (rs.next()) {

                String mName = rs.getString("md_name");
                String enName = rs.getString("en_name");
                String mType = rs.getString("md_type");

                String data[] = {mName, enName, mType, Float.toString(rs.getFloat("t_f_amount"))};

                tm.addRow(data);

            }
            rs = st.executeQuery("select en_name from engine");
            while (rs.next()) {
                String enname = rs.getString("en_name");
                jComboBox1.addItem(enname);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 10, 170, 40);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 430, 55, 23);

        jButton2.setText("Add Model");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 430, 140, 30);

        jLabel2.setText("Model Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 230, 100, 14);

        jLabel3.setText("Model Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 290, 110, 14);

        jLabel4.setText("Total Fuel Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 350, 150, 14);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(400, 230, 6, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(400, 290, 6, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(400, 350, 6, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Name", "Engine Name", "Model Type", "Total Fuel"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 80, 452, 100);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(400, 390, 170, 20);

        jLabel6.setText("Engine Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 390, 110, 14);

        jLabel5.setText("Dont currently have the engine? ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 480, 170, 30);

        jButton3.setText("Click here to add new engine");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 510, 220, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            Connection con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            Statement st = con.createStatement();

            String mn = jTextField2.getText();
            String en = jComboBox1.getSelectedItem().toString();
            String mt = jTextField3.getText();
            float tfa = Float.valueOf(jTextField4.getText().toString());

            String query = "insert into model values('" + mn + "','" + en + "','" + mt + "'," + tfa + ")";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "data added successfully");

            ResultSet rs = st.executeQuery("select * from model");
            while (rs.next()) {

                String mName = rs.getString("md_name");
                String eName = rs.getString("en_name");
                String mType = rs.getString("md_type");
                String data[] = {mName, eName, mType, Float.toString(rs.getFloat("t_f_amount"))};
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.addRow(data);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (back == 0) {
            managerActivity ma = new managerActivity();
            ma.show();
            dispose();
        } else {
            addVehicle av = new addVehicle();
            av.show();
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Engine ae = new Engine(m_username, 1, back);
        ae.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
