/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project3_1;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Drive extends javax.swing.JFrame {

    public Connection con;
    ResultSet rs = null;
    Statement st;
    String u_username = "u";

    public Drive() {
        initComponents();
        setSize(1000,700);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            st = con.createStatement();
            jLabel2.setText(u_username);
            rs = st.executeQuery("select * from manager where m_username='" + u_username + "'");
            if (rs.next()) {
                jLabel1.setText("Welcome " + rs.getString("u_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        alldata();
        setDate();
    }

    public Drive(String x) {
        initComponents();
        u_username = x;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            st = con.createStatement();
            jLabel2.setText(u_username);
            rs = st.executeQuery("select * from manager where m_username='" + u_username + "'");
            if (rs.next()) {
                jLabel1.setText("Welcome " + rs.getString("u_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        alldata();
        setDate();
    }
    
    public void setDate(){
        for (int i = 1; i <= 31; i++) {
            jComboBox3.addItem(Integer.toString(i));
        }
    }

    public void alldata() {
        try {
            rs = st.executeQuery("select * from vehicles");
            while (rs.next()) {
                String data[] = {String.valueOf(rs.getInt("v_id")), Float.toString(rs.getFloat("c_f_amount"))};
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.addRow(data);
                jComboBoxVehicle.addItem(String.valueOf(rs.getInt("v_id")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            rs = st.executeQuery("select * from drives where u_username='" + u_username + "'");
            while (rs.next()) {
                /*DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
                String strDate = dateFormat.format(rs.getDate("d_date"));*/
                String data[] = {String.valueOf(rs.getInt("v_id")),rs.getDate("d_date").toString(),String.valueOf(rs.getInt("d_distance")),rs.getTime("d_time").toString(), Float.toString(rs.getFloat("f_amount"))};
                DefaultTableModel tm2 = (DefaultTableModel) jTable4.getModel();
                tm2.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jMinute = new javax.swing.JTextField();
        jSecond = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        jHour = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBoxVehicle = new javax.swing.JComboBox<>();
        jLabelMon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFuelAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle Id", "Current Fuel"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(610, 40, 272, 136);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Second");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(133, 475, 43, 23);

        jMinute.setText("00");
        getContentPane().add(jMinute);
        jMinute.setBounds(182, 431, 50, 30);

        jSecond.setText("00");
        getContentPane().add(jSecond);
        jSecond.setBounds(182, 473, 50, 30);

        jLabelYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear.setText("Year");
        getContentPane().add(jLabelYear);
        jLabelYear.setBounds(247, 396, 43, 23);

        jHour.setText("00");
        getContentPane().add(jHour);
        jHour.setBounds(182, 394, 50, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(296, 394, 80, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehicle ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 230, 76, 36);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(296, 429, 80, 30);

        getContentPane().add(jComboBoxVehicle);
        jComboBoxVehicle.setBounds(300, 230, 110, 40);

        jLabelMon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMon.setText("Month");
        getContentPane().add(jLabelMon);
        jLabelMon.setBounds(247, 431, 43, 23);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 610, 59, 25);

        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(296, 464, 80, 30);

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 610, 57, 25);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("day");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(247, 466, 43, 23);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Distance");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 280, 80, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hour");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(133, 396, 43, 23);

        jAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jAmount.setText("50");
        getContentPane().add(jAmount);
        jAmount.setBounds(300, 290, 70, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Minute");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(133, 433, 43, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("u");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(398, 16, 152, 21);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome u");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(59, 52, 304, 32);

        jFuelAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFuelAmount.setText("50");
        getContentPane().add(jFuelAmount);
        jFuelAmount.setBounds(300, 340, 70, 30);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("fuel amount");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 330, 130, 40);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "vehicle id", "date", "distance", "time", "fuel consumed"
            }
        ));
        jScrollPane2.setViewportView(jTable4);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 270, 450, 202);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/photo-1605282003441-a966bb348137.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1000, 690);

        setBounds(0, 0, 1023, 748);
    }// </editor-fold>//GEN-END:initComponents
       
    ArrayList<String> month31 = new ArrayList<>(Arrays.asList("1", "3", "5", "7", "8", "10", "12")); 
    ArrayList<String> month30 = new ArrayList<>(Arrays.asList("4", "6", "9", "11")); 
    ArrayList<String> leapYears = new ArrayList<>(Arrays.asList("2000", "2004", "2008", "2012", "2016", "2020")); 
    
    private void comboBoxSelected()
    {
        jComboBox3.removeItem("29");
        jComboBox3.removeItem("30");
        jComboBox3.removeItem("31");
        if (month31.contains(jComboBox2.getSelectedItem())) {
            
            jComboBox3.addItem("29");
            jComboBox3.addItem("30");
            jComboBox3.addItem("31");
            
        } else if (month30.contains(jComboBox2.getSelectedItem())) {
            jComboBox3.addItem("29");
            jComboBox3.addItem("30");
        } else if (leapYears.contains(jComboBox1.getSelectedItem())) {
            jComboBox3.addItem("29");
        }  
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        dispose();
        new userActivity(u_username).show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int lh = jHour.getText().length(), lm = jMinute.getText().length(), ls = jSecond.getText().length(), la = jAmount.getText().length(), dw = 1;
        System.out.println(la);
        if (lh == 0 || lm == 0 || ls == 0 || la == 0) {
            dw = 0;
            JOptionPane.showMessageDialog(null, "No field can be empty", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        if (dw == 1) {
            for (int i = 0; i < lh; i++) {
                if (jHour.getText().charAt(i) == '0'
                        || jHour.getText().charAt(i) == '1'
                        || jHour.getText().charAt(i) == '2'
                        || jHour.getText().charAt(i) == '3'
                        || jHour.getText().charAt(i) == '4'
                        || jHour.getText().charAt(i) == '5'
                        || jHour.getText().charAt(i) == '6'
                        || jHour.getText().charAt(i) == '7'
                        || jHour.getText().charAt(i) == '8'
                        || jHour.getText().charAt(i) == '9') {

                } else {
                    JOptionPane.showMessageDialog(null, "Enter hour correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jHour.setText("00");
                    dw = 0;
                    break;
                }
            }
        }
        if (dw == 1) {
            for (int i = 0; i < lm; i++) {
                if (jMinute.getText().charAt(i) == '0'
                        || jMinute.getText().charAt(i) == '1'
                        || jMinute.getText().charAt(i) == '2'
                        || jMinute.getText().charAt(i) == '3'
                        || jMinute.getText().charAt(i) == '4'
                        || jMinute.getText().charAt(i) == '5'
                        || jMinute.getText().charAt(i) == '6'
                        || jMinute.getText().charAt(i) == '7'
                        || jMinute.getText().charAt(i) == '8'
                        || jMinute.getText().charAt(i) == '9') {

                } else {
                    dw = 0;
                    JOptionPane.showMessageDialog(null, "Enter Minute correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jMinute.setText("00");
                    break;
                }
            }
        }
        if (dw == 1) {
            for (int i = 0; i < ls; i++) {
                if (jSecond.getText().charAt(i) == '0'
                        || jSecond.getText().charAt(i) == '1'
                        || jSecond.getText().charAt(i) == '2'
                        || jSecond.getText().charAt(i) == '3'
                        || jSecond.getText().charAt(i) == '4'
                        || jSecond.getText().charAt(i) == '5'
                        || jSecond.getText().charAt(i) == '6'
                        || jSecond.getText().charAt(i) == '7'
                        || jSecond.getText().charAt(i) == '8'
                        || jSecond.getText().charAt(i) == '9') {

                } else {
                    dw = 0;
                    JOptionPane.showMessageDialog(null, "Enter Second correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jSecond.setText("00");
                    break;
                }
            }
        }
        if (dw == 1) {
            for (int i = 0; i < la; i++) {
                if (jAmount.getText().charAt(i) == '0'
                        || jAmount.getText().charAt(i) == '1'
                        || jAmount.getText().charAt(i) == '2'
                        || jAmount.getText().charAt(i) == '3'
                        || jAmount.getText().charAt(i) == '4'
                        || jAmount.getText().charAt(i) == '5'
                        || jAmount.getText().charAt(i) == '6'
                        || jAmount.getText().charAt(i) == '7'
                        || jAmount.getText().charAt(i) == '8'
                        || jAmount.getText().charAt(i) == '9') {

                } else {
                    dw = 0;
                    JOptionPane.showMessageDialog(null, "Enter Amount correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jAmount.setText("00");
                    break;
                }
            }
        }
        if (dw == 1) {
            try {
                Float.valueOf(jFuelAmount.getText().toString());
            } catch (Exception e) {
                //e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Enter Fuel amount correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jFuelAmount.setText("00");
            }
        }
        if (dw == 0) {

        } else {
            float rfa = 0;
            try {
                rs = st.executeQuery("select * from vehicles where v_id=" + jComboBoxVehicle.getSelectedItem().toString());
                while (rs.next()) {
                    rfa = rs.getFloat("c_f_amount");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            if (Integer.parseInt(jHour.getText()) > 24 || jHour.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter hour correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jHour.setText("00");
            } else if (Integer.parseInt(jMinute.getText()) > 60 || jMinute.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter minute correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jHour.setText("00");
            } else if (Integer.parseInt(jSecond.getText()) > 60 || jSecond.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter second correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jHour.setText("00");
            } else if (jAmount.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter amount", "Error", JOptionPane.INFORMATION_MESSAGE);
                jAmount.setText("00");
            } else if (Float.valueOf(jFuelAmount.getText().toString()) > rfa) {
                JOptionPane.showMessageDialog(null, "fuel amount can't be more than " + rfa, "Error", JOptionPane.INFORMATION_MESSAGE);
                jAmount.setText("00");
            } else {
                String etime = jHour.getText() + ":" + jMinute.getText() + ":" + jSecond.getText() + ".00";
                String edate = jComboBox1.getSelectedItem() + "-" + jComboBox2.getSelectedItem() + "-" + jComboBox3.getSelectedItem();
                try {
                    rfa = rfa - Float.valueOf(jFuelAmount.getText().toString());
                    if (st.executeUpdate("INSERT INTO drives values ('" + u_username + "'," + Integer.parseInt(jComboBoxVehicle.getSelectedItem().toString()) + ",'" + edate + "'," + Integer.parseInt(jAmount.getText()) + ",'" + etime + "'," + Float.valueOf(jFuelAmount.getText().toString()) + ")") == 1
                            && st.executeUpdate("UPDATE vehicles set c_f_amount=" + rfa + " where v_id=" + Integer.parseInt(jComboBoxVehicle.getSelectedItem().toString()) + "") == 1) {
                        JOptionPane.showMessageDialog(null, "data inserted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                        tm.setRowCount(0);
                        DefaultTableModel tm1 = (DefaultTableModel) jTable4.getModel();
                        tm1.setRowCount(0);
                        alldata();
                    }

                    //"Integer.parseInt(jAmount.getText()"
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        comboBoxSelected();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        comboBoxSelected();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBoxVehicle;
    private javax.swing.JTextField jFuelAmount;
    private javax.swing.JTextField jHour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMon;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JTextField jMinute;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jSecond;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
