/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project3_1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class FilterFrame extends javax.swing.JFrame {

    /**
     * Creates new form FilterFrame
     */
    
    int searchBy;
    int search;
    ArrayList<Integer> searchContentsU;
    ArrayList<Integer> searchContentsV;
    DynamicSearch ds;
    
    public FilterFrame(){
        
    }    
    public FilterFrame(int _searchBy, int _search, ArrayList<Integer> _searchContentsU, ArrayList<Integer> _searchContentsV, DynamicSearch _ds) {
        initComponents();
        searchBy = _searchBy;
        search = _search;
        searchContentsU = _searchContentsU;
        searchContentsV = _searchContentsV;
        ds = _ds;
        
        jRadioButtonUser.setSelected(search == 0);
        jRadioButtonVahicle.setSelected(search == 1);
        jRadioButtonName.setSelected(searchBy == 0);
        jRadioButtonID.setSelected(searchBy == 1);
        
        jPanel1.setVisible(search == 0);
        jPanel2.setVisible(search == 1);

        
        for( int value : searchContentsU ) {
            switch(value){
                case 1: jCheckBoxUN.setSelected(true); break;
                case 2: jCheckBoxName.setSelected(true); break;
                case 3: jCheckBoxAge.setSelected(true); break;
                case 4: jCheckBoxTD.setSelected(true); break;
                case 5: jCheckBoxTF.setSelected(true); break;
                case 6: jCheckBoxAS.setSelected(true); break;
                default: break;
            }
        } 
        for( int value : searchContentsV ) {
            switch(value){
                case 1: jCheckBoxID.setSelected(true); break;
                case 2: jCheckBoxColor.setSelected(true); break;
                case 3: jCheckBoxMN.setSelected(true); break;
                case 4: jCheckBoxMT.setSelected(true); break;
                case 5: jCheckBoxFN.setSelected(true); break;
                case 6: jCheckBoxC.setSelected(true); break;
                case 7: jCheckBoxFA.setSelected(true); break;
                case 8: jCheckBoxFP.setSelected(true); break;
                case 9: jCheckBoxEN.setSelected(true); break;
                default: break;
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSearchBy = new javax.swing.ButtonGroup();
        buttonGroupSearch = new javax.swing.ButtonGroup();
        jLabelSearchOpSearchBy = new javax.swing.JLabel();
        jRadioButtonName = new javax.swing.JRadioButton();
        jRadioButtonID = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelSearchSpecific = new javax.swing.JLabel();
        jCheckBoxName = new javax.swing.JCheckBox();
        jCheckBoxUN = new javax.swing.JCheckBox();
        jCheckBoxAS = new javax.swing.JCheckBox();
        jCheckBoxAge = new javax.swing.JCheckBox();
        jCheckBoxTD = new javax.swing.JCheckBox();
        jCheckBoxTF = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabelSearchSpecific1 = new javax.swing.JLabel();
        jCheckBoxMN = new javax.swing.JCheckBox();
        jCheckBoxID = new javax.swing.JCheckBox();
        jCheckBoxFP = new javax.swing.JCheckBox();
        jCheckBoxColor = new javax.swing.JCheckBox();
        jCheckBoxFN = new javax.swing.JCheckBox();
        jCheckBoxMT = new javax.swing.JCheckBox();
        jCheckBoxFA = new javax.swing.JCheckBox();
        jCheckBoxC = new javax.swing.JCheckBox();
        jCheckBoxEN = new javax.swing.JCheckBox();
        jLabelSearchOpSearchBy1 = new javax.swing.JLabel();
        jRadioButtonUser = new javax.swing.JRadioButton();
        jRadioButtonVahicle = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(420, 300));
        setMinimumSize(new java.awt.Dimension(420, 300));
        setPreferredSize(new java.awt.Dimension(420, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSearchOpSearchBy.setText("Search By:");
        getContentPane().add(jLabelSearchOpSearchBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, 20));

        buttonGroupSearchBy.add(jRadioButtonName);
        jRadioButtonName.setText("Name");
        jRadioButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNameActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        buttonGroupSearchBy.add(jRadioButtonID);
        jRadioButtonID.setText("Id");
        jRadioButtonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIDActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSearchSpecific.setText("Search Specific:");
        jPanel1.add(jLabelSearchSpecific, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCheckBoxName.setText("Name");
        jCheckBoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxNameActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jCheckBoxUN.setText("User Name");
        jCheckBoxUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUNActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jCheckBoxAS.setText("Approve State");
        jCheckBoxAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxASActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jCheckBoxAge.setText("Age");
        jCheckBoxAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAgeActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jCheckBoxTD.setText("Total Distance");
        jCheckBoxTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTDActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jCheckBoxTF.setText("Total Fuel Used");
        jCheckBoxTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTFActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 190));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSearchSpecific1.setText("Search Specific:");
        jPanel2.add(jLabelSearchSpecific1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCheckBoxMN.setText("Model Name");
        jCheckBoxMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMNActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jCheckBoxID.setText("ID");
        jCheckBoxID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIDActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jCheckBoxFP.setText("Fuel Price");
        jCheckBoxFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFPActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jCheckBoxColor.setText("Color");
        jCheckBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxColorActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jCheckBoxFN.setText("Fuel Name");
        jCheckBoxFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFNActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxFN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jCheckBoxMT.setText("Model Type");
        jCheckBoxMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMTActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        jCheckBoxFA.setText("Fuel Amount");
        jCheckBoxFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFAActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jCheckBoxC.setText("Capacity");
        jCheckBoxC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jCheckBoxEN.setText("Engine Name");
        jCheckBoxEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxENActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 360, 190));

        jLabelSearchOpSearchBy1.setText("Search:");
        getContentPane().add(jLabelSearchOpSearchBy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 20));

        buttonGroupSearch.add(jRadioButtonUser);
        jRadioButtonUser.setText("User");
        jRadioButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUserActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        buttonGroupSearch.add(jRadioButtonVahicle);
        jRadioButtonVahicle.setText("Vahicle");
        jRadioButtonVahicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVahicleActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonVahicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        setSize(new java.awt.Dimension(436, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNameActionPerformed
        ds.setSearchBy(searchBy = 0);
    }//GEN-LAST:event_jRadioButtonNameActionPerformed

    private void jRadioButtonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIDActionPerformed
        ds.setSearchBy(searchBy = 1);
    }//GEN-LAST:event_jRadioButtonIDActionPerformed

    private void jCheckBoxAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAgeActionPerformed
        if(!searchContentsU.contains(3)){
            searchContentsU.add(3);
            ds.setArrayListU(searchContentsU);
        }
        else{
            searchContentsU.remove(Integer.valueOf(3));
        }
        System.out.println(searchContentsU);
    }//GEN-LAST:event_jCheckBoxAgeActionPerformed

    private void jCheckBoxTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTDActionPerformed
        if(!searchContentsU.contains(4)){
            searchContentsU.add(4);
            ds.setArrayListU(searchContentsU);
        }
        else{
            searchContentsU.remove(Integer.valueOf(4));
        }
        System.out.println(searchContentsU);
    }//GEN-LAST:event_jCheckBoxTDActionPerformed

    private void jCheckBoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxNameActionPerformed
        if(!searchContentsU.contains(2)){
            searchContentsU.add(2);
            ds.setArrayListU(searchContentsU);
        }
        else{
            searchContentsU.remove(Integer.valueOf(2));
        }
        System.out.println(searchContentsU);
    }//GEN-LAST:event_jCheckBoxNameActionPerformed

    private void jCheckBoxASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxASActionPerformed
        if(!searchContentsU.contains(6)){
            searchContentsU.add(6);
            ds.setArrayListU(searchContentsU);
        }
        else{
            searchContentsU.remove(Integer.valueOf(6));
        }
        System.out.println(searchContentsU);
    }//GEN-LAST:event_jCheckBoxASActionPerformed

    private void jCheckBoxTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTFActionPerformed
        if(!searchContentsU.contains(5)){
            searchContentsU.add(5);
            ds.setArrayListU(searchContentsU);
        }
        else{
            searchContentsU.remove(Integer.valueOf(5));
        }
    }//GEN-LAST:event_jCheckBoxTFActionPerformed

    private void jCheckBoxUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUNActionPerformed
        if(!searchContentsU.contains(1)){
            searchContentsU.add(1);
            ds.setArrayListU(searchContentsU);
        }
        else{
            searchContentsU.remove(Integer.valueOf(1));
        }
        System.out.println(searchContentsU);
    }//GEN-LAST:event_jCheckBoxUNActionPerformed

    private void jCheckBoxMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMNActionPerformed
        if(!searchContentsV.contains(3)){
            searchContentsV.add(3);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(3));
        }
    }//GEN-LAST:event_jCheckBoxMNActionPerformed

    private void jCheckBoxIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIDActionPerformed
        if(!searchContentsV.contains(1)){
            searchContentsV.add(1);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(1));
        }
    }//GEN-LAST:event_jCheckBoxIDActionPerformed

    private void jCheckBoxFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFPActionPerformed
        if(!searchContentsV.contains(8)){
            searchContentsV.add(8);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(8));
        }
    }//GEN-LAST:event_jCheckBoxFPActionPerformed

    private void jCheckBoxColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxColorActionPerformed
        if(!searchContentsV.contains(2)){
            searchContentsV.add(2);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(2));
        }
    }//GEN-LAST:event_jCheckBoxColorActionPerformed

    private void jCheckBoxFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFNActionPerformed
        if(!searchContentsV.contains(5)){
            searchContentsV.add(5);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(5));
        }
    }//GEN-LAST:event_jCheckBoxFNActionPerformed

    private void jCheckBoxMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMTActionPerformed
        if(!searchContentsV.contains(4)){
            searchContentsV.add(4);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(4));
        }
    }//GEN-LAST:event_jCheckBoxMTActionPerformed

    private void jRadioButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUserActionPerformed
        ds.setSearch(search = 0);
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_jRadioButtonUserActionPerformed

    private void jRadioButtonVahicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVahicleActionPerformed
        ds.setSearch(search = 1);
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jRadioButtonVahicleActionPerformed

    private void jCheckBoxFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFAActionPerformed
        if(!searchContentsV.contains(7)){
            searchContentsV.add(7);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(7));
        }
    }//GEN-LAST:event_jCheckBoxFAActionPerformed

    private void jCheckBoxCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCActionPerformed
        if(!searchContentsV.contains(6)){
            searchContentsV.add(6);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(6));
        }
    }//GEN-LAST:event_jCheckBoxCActionPerformed

    private void jCheckBoxENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxENActionPerformed
        if(!searchContentsV.contains(9)){
            searchContentsV.add(9);
            ds.setArrayListV(searchContentsV);
        }
        else{
            searchContentsV.remove(Integer.valueOf(9));
        }
    }//GEN-LAST:event_jCheckBoxENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FilterFrame().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSearch;
    private javax.swing.ButtonGroup buttonGroupSearchBy;
    private javax.swing.JCheckBox jCheckBoxAS;
    private javax.swing.JCheckBox jCheckBoxAge;
    private javax.swing.JCheckBox jCheckBoxC;
    private javax.swing.JCheckBox jCheckBoxColor;
    private javax.swing.JCheckBox jCheckBoxEN;
    private javax.swing.JCheckBox jCheckBoxFA;
    private javax.swing.JCheckBox jCheckBoxFN;
    private javax.swing.JCheckBox jCheckBoxFP;
    private javax.swing.JCheckBox jCheckBoxID;
    private javax.swing.JCheckBox jCheckBoxMN;
    private javax.swing.JCheckBox jCheckBoxMT;
    private javax.swing.JCheckBox jCheckBoxName;
    private javax.swing.JCheckBox jCheckBoxTD;
    private javax.swing.JCheckBox jCheckBoxTF;
    private javax.swing.JCheckBox jCheckBoxUN;
    private javax.swing.JLabel jLabelSearchOpSearchBy;
    private javax.swing.JLabel jLabelSearchOpSearchBy1;
    private javax.swing.JLabel jLabelSearchSpecific;
    private javax.swing.JLabel jLabelSearchSpecific1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonID;
    private javax.swing.JRadioButton jRadioButtonName;
    private javax.swing.JRadioButton jRadioButtonUser;
    private javax.swing.JRadioButton jRadioButtonVahicle;
    // End of variables declaration//GEN-END:variables
}
