/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project3_1;

import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class request extends javax.swing.JFrame {

    public Connection con;
    ResultSet rs = null;
    Statement st;
    String u_username = "u";
    String v, f, p;
    float r,fa,price;

    public request() {
        initComponents();
        setSize(1000,580);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            st = con.createStatement();
            jLabel2.setText(u_username);
            rs = st.executeQuery("select * from user_info where u_username='" + u_username + "'");
            if (rs.next()) {
                jLabel1.setText("Welcome " + rs.getString("u_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        alldata();
        jAmount.setEnabled(false);
    }

    public request(String x) {
        initComponents();
        u_username = x;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            st = con.createStatement();
            jLabel2.setText(u_username);
            rs = st.executeQuery("select * from user_info where u_username='" + u_username + "'");
            if (rs.next()) {
                jLabel1.setText("Welcome " + rs.getString("u_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        alldata();
        jAmount.setEnabled(false);
    }

    public void alldata() {
        try {
            rs = st.executeQuery("select v.v_id, v.c_f_amount , m.t_f_amount, e.f_name, f.f_price from\n"
                    + "vehicles v inner join model m on v.md_name=m.md_name\n"
                    + " INNER JOIN engine e ON m.en_name = e.en_name\n"
                    + " inner join fuels f on e.f_name=f.f_name");
            while (rs.next()) {
                String data[] = {String.valueOf(rs.getInt("v_id")), Float.toString(rs.getFloat("c_f_amount")), Float.toString(rs.getFloat("t_f_amount")), rs.getString("f_name"), Float.toString(rs.getFloat("f_price"))};
                DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
                tm.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMinute = new javax.swing.JTextField();
        jSecond = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        jHour = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelMon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelV = new javax.swing.JLabel();
        jLabelR = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelF = new javax.swing.JLabel();
        jLabelTC = new javax.swing.JLabel();
        jLabelCost = new javax.swing.JLabel();
        jAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(280, 380, 49, 26);

        jButton2.setText("Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(216, 457, 89, 29);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("day");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(169, 383, 70, 23);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("refill type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(42, 174, 90, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hour");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 304, 60, 23);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "refill type", "fuel name", "fuel amount"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable4);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(470, 300, 470, 202);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Minute");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(39, 341, 60, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("u");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(663, 16, 152, 21);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome u");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(33, 37, 304, 49);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Second");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(39, 383, 60, 23);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("refill amount");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(42, 213, 110, 30);

        jMinute.setText("00");
        getContentPane().add(jMinute);
        jMinute.setBounds(105, 339, 24, 26);

        jSecond.setText("00");
        getContentPane().add(jSecond);
        jSecond.setBounds(105, 381, 24, 26);

        jLabelYear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYear.setText("Year");
        getContentPane().add(jLabelYear);
        jLabelYear.setBounds(169, 304, 43, 23);

        jHour.setText("00");
        getContentPane().add(jHour);
        jHour.setBounds(105, 302, 24, 26);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(280, 300, 67, 26);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehicle ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(42, 104, 76, 24);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(280, 340, 49, 26);

        jLabelMon.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMon.setText("Month");
        getContentPane().add(jLabelMon);
        jLabelMon.setBounds(169, 346, 70, 23);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(42, 457, 65, 29);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "vehicle", "current fuel", "fuel capacity", "fuel type", "fuel price"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(470, 90, 465, 191);

        jLabelV.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelV);
        jLabelV.setBounds(180, 100, 101, 24);

        jLabelR.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelR);
        jLabelR.setBounds(170, 170, 101, 30);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(311, 174, 110, 0);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("fuel type");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(42, 137, 80, 33);

        jLabelF.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelF);
        jLabelF.setBounds(160, 130, 101, 33);

        jLabelTC.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelTC);
        jLabelTC.setBounds(170, 260, 101, 23);

        jLabelCost.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCost.setText("Total cost");
        getContentPane().add(jLabelCost);
        jLabelCost.setBounds(42, 255, 76, 23);

        jAmount.setText("1");
        jAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmountActionPerformed(evt);
            }
        });
        getContentPane().add(jAmount);
        jAmount.setBounds(170, 220, 104, 26);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/photo-1605282003441-a966bb348137.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 990, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jAmount.getText().toString().equals(null))
        {
            jLabelTC.setText(String.valueOf("0"));
        } else{
            price = Float.parseFloat(p) * fa * Float.parseFloat(jAmount.getText().toString());
            jLabelTC.setText(String.valueOf(price));
        }
        int lh = jHour.getText().length(), lm = jMinute.getText().length(), ls = jSecond.getText().length(), la = jAmount.getText().length(), dw = 1;
        System.out.println(la);
        if (lh == 0 || lm == 0 || ls == 0 || la == 0) {
            dw = 0;
            JOptionPane.showMessageDialog(null, "No field can be empty", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        if (dw == 1) {
            for (int i = 0; i < lh; i++) {
                if (jHour.getText().charAt(i) == '0'
                        || jHour.getText().charAt(i) == '1'
                        || jHour.getText().charAt(i) == '2'
                        || jHour.getText().charAt(i) == '3'
                        || jHour.getText().charAt(i) == '4'
                        || jHour.getText().charAt(i) == '5'
                        || jHour.getText().charAt(i) == '6'
                        || jHour.getText().charAt(i) == '7'
                        || jHour.getText().charAt(i) == '8'
                        || jHour.getText().charAt(i) == '9') {

                } else {
                    JOptionPane.showMessageDialog(null, "Enter hour correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jHour.setText("00");
                    dw = 0;
                    break;
                }
            }
        }
        if (dw == 1) {
            for (int i = 0; i < lm; i++) {
                if (jMinute.getText().charAt(i) == '0'
                        || jMinute.getText().charAt(i) == '1'
                        || jMinute.getText().charAt(i) == '2'
                        || jMinute.getText().charAt(i) == '3'
                        || jMinute.getText().charAt(i) == '4'
                        || jMinute.getText().charAt(i) == '5'
                        || jMinute.getText().charAt(i) == '6'
                        || jMinute.getText().charAt(i) == '7'
                        || jMinute.getText().charAt(i) == '8'
                        || jMinute.getText().charAt(i) == '9') {

                } else {
                    dw = 0;
                    JOptionPane.showMessageDialog(null, "Enter Minute correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jMinute.setText("00");
                    break;
                }
            }
        }
        if (dw == 1) {
            for (int i = 0; i < ls; i++) {
                if (jSecond.getText().charAt(i) == '0'
                        || jSecond.getText().charAt(i) == '1'
                        || jSecond.getText().charAt(i) == '2'
                        || jSecond.getText().charAt(i) == '3'
                        || jSecond.getText().charAt(i) == '4'
                        || jSecond.getText().charAt(i) == '5'
                        || jSecond.getText().charAt(i) == '6'
                        || jSecond.getText().charAt(i) == '7'
                        || jSecond.getText().charAt(i) == '8'
                        || jSecond.getText().charAt(i) == '9') {

                } else {
                    dw = 0;
                    JOptionPane.showMessageDialog(null, "Enter Second correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jSecond.setText("00");
                    break;
                }
            }
        }
        if (dw == 1) {
            for (int i = 0; i < la; i++) {
                if (jAmount.getText().charAt(i) == '0'
                        || jAmount.getText().charAt(i) == '1'
                        || jAmount.getText().charAt(i) == '2'
                        || jAmount.getText().charAt(i) == '3'
                        || jAmount.getText().charAt(i) == '4'
                        || jAmount.getText().charAt(i) == '5'
                        || jAmount.getText().charAt(i) == '6'
                        || jAmount.getText().charAt(i) == '7'
                        || jAmount.getText().charAt(i) == '8'
                        || jAmount.getText().charAt(i) == '9') {

                } else {
                    dw = 0;
                    JOptionPane.showMessageDialog(null, "Enter Amount correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                    jAmount.setText("00");
                    break;
                }
            }
        }
        /*if (dw == 1) {
            try {
                Float.valueOf(jFuelAmount.getText().toString());
            } catch (Exception e) {
                //e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Enter Fuel amount correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jFuelAmount.setText("00");
            }
        }*/
        if (dw == 0) {

        } else {

            if (Integer.parseInt(jHour.getText()) > 24 || jHour.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter hour correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jHour.setText("00");
            } else if (Integer.parseInt(jMinute.getText()) > 60 || jMinute.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter minute correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jHour.setText("00");
            } else if (Integer.parseInt(jSecond.getText()) > 60 || jSecond.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter second correctly!", "Error", JOptionPane.INFORMATION_MESSAGE);
                jHour.setText("00");
            } else if (jLabelV.getText().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "Choose a vehicle", "Error", JOptionPane.INFORMATION_MESSAGE);               
            }  else if (jLabelR.getText().toString().equals("")) {
                JOptionPane.showMessageDialog(null, "Choose a refill type", "Error", JOptionPane.INFORMATION_MESSAGE);               
            } else if (jAmount.getText().equals(null)) {
                JOptionPane.showMessageDialog(null, "Enter amount", "Error", JOptionPane.INFORMATION_MESSAGE);
                jAmount.setText("00");
            } else if (Integer.parseInt(jAmount.getText().toString())*fa>r) {
                JOptionPane.showMessageDialog(null, "Amount can't be more than remaining fuel", "Error", JOptionPane.INFORMATION_MESSAGE);
                jAmount.setText("00");
                jLabelTC.setText("00");
            } else if (Integer.parseInt(jAmount.getText().toString())==0) {
                JOptionPane.showMessageDialog(null, "refill amount can't be zero", "Error", JOptionPane.INFORMATION_MESSAGE);
                jAmount.setText("00");
            }  else {
                String etime = jHour.getText() + ":" + jMinute.getText() + ":" + jSecond.getText() + ".00";
                String edate = jComboBox1.getSelectedItem() + "-" + jComboBox2.getSelectedItem() + "-" + jComboBox3.getSelectedItem();
                try {;
                    if (st.executeUpdate("insert into request values ('"+u_username+"',"+v+","
                            +jLabelR.getText().toString()+","+Integer.parseInt(jAmount.getText().toString())
                            +",'"+edate+"','"+etime+"',"+fa+","+price+",'unseen')") == 1) {
                        JOptionPane.showMessageDialog(null, "data inserted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        
                    }

                    //"Integer.parseInt(jAmount.getText()"
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedItem().equals("2") && (jComboBox1.getSelectedItem().equals("2000")
                || jComboBox1.getSelectedItem().equals("2004")
                || jComboBox1.getSelectedItem().equals("2008")
                || jComboBox1.getSelectedItem().equals("2012")
                || jComboBox1.getSelectedItem().equals("2016")
                || jComboBox1.getSelectedItem().equals("2020"))) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("1");
            jComboBox3.addItem("2");
            jComboBox3.addItem("3");
            jComboBox3.addItem("4");
            jComboBox3.addItem("5");
            jComboBox3.addItem("6");
            jComboBox3.addItem("7");
            jComboBox3.addItem("8");
            jComboBox3.addItem("9");
            jComboBox3.addItem("10");
            jComboBox3.addItem("11");
            jComboBox3.addItem("12");
            jComboBox3.addItem("13");
            jComboBox3.addItem("14");
            jComboBox3.addItem("15");
            jComboBox3.addItem("16");
            jComboBox3.addItem("17");
            jComboBox3.addItem("18");
            jComboBox3.addItem("19");
            jComboBox3.addItem("20");
            jComboBox3.addItem("21");
            jComboBox3.addItem("22");
            jComboBox3.addItem("23");
            jComboBox3.addItem("24");
            jComboBox3.addItem("25");
            jComboBox3.addItem("26");
            jComboBox3.addItem("27");
            jComboBox3.addItem("28");
            jComboBox3.addItem("29");
            jComboBox3.setSelectedItem("1");
        } else if (jComboBox2.getSelectedItem().equals("2")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("1");
            jComboBox3.addItem("2");
            jComboBox3.addItem("3");
            jComboBox3.addItem("4");
            jComboBox3.addItem("5");
            jComboBox3.addItem("6");
            jComboBox3.addItem("7");
            jComboBox3.addItem("8");
            jComboBox3.addItem("9");
            jComboBox3.addItem("10");
            jComboBox3.addItem("11");
            jComboBox3.addItem("12");
            jComboBox3.addItem("13");
            jComboBox3.addItem("14");
            jComboBox3.addItem("15");
            jComboBox3.addItem("16");
            jComboBox3.addItem("17");
            jComboBox3.addItem("18");
            jComboBox3.addItem("19");
            jComboBox3.addItem("20");
            jComboBox3.addItem("21");
            jComboBox3.addItem("22");
            jComboBox3.addItem("23");
            jComboBox3.addItem("24");
            jComboBox3.addItem("25");
            jComboBox3.addItem("26");
            jComboBox3.addItem("27");
            jComboBox3.addItem("28");
            jComboBox3.setSelectedItem("1");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedItem().equals("1")
                || jComboBox2.getSelectedItem().equals("3")
                || jComboBox2.getSelectedItem().equals("5")
                || jComboBox2.getSelectedItem().equals("7")
                || jComboBox2.getSelectedItem().equals("8")
                || jComboBox2.getSelectedItem().equals("10")
                || jComboBox2.getSelectedItem().equals("12")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("1");
            jComboBox3.addItem("2");
            jComboBox3.addItem("3");
            jComboBox3.addItem("4");
            jComboBox3.addItem("5");
            jComboBox3.addItem("6");
            jComboBox3.addItem("7");
            jComboBox3.addItem("8");
            jComboBox3.addItem("9");
            jComboBox3.addItem("10");
            jComboBox3.addItem("11");
            jComboBox3.addItem("12");
            jComboBox3.addItem("13");
            jComboBox3.addItem("14");
            jComboBox3.addItem("15");
            jComboBox3.addItem("16");
            jComboBox3.addItem("17");
            jComboBox3.addItem("18");
            jComboBox3.addItem("19");
            jComboBox3.addItem("20");
            jComboBox3.addItem("21");
            jComboBox3.addItem("22");
            jComboBox3.addItem("23");
            jComboBox3.addItem("24");
            jComboBox3.addItem("25");
            jComboBox3.addItem("26");
            jComboBox3.addItem("27");
            jComboBox3.addItem("28");
            jComboBox3.addItem("29");
            jComboBox3.addItem("30");
            jComboBox3.addItem("31");
            jComboBox3.setSelectedItem("1");
        } else if (jComboBox2.getSelectedItem().equals("4")
                || jComboBox2.getSelectedItem().equals("6")
                || jComboBox2.getSelectedItem().equals("9")
                || jComboBox2.getSelectedItem().equals("11")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("1");
            jComboBox3.addItem("2");
            jComboBox3.addItem("3");
            jComboBox3.addItem("4");
            jComboBox3.addItem("5");
            jComboBox3.addItem("6");
            jComboBox3.addItem("7");
            jComboBox3.addItem("8");
            jComboBox3.addItem("9");
            jComboBox3.addItem("10");
            jComboBox3.addItem("11");
            jComboBox3.addItem("12");
            jComboBox3.addItem("13");
            jComboBox3.addItem("14");
            jComboBox3.addItem("15");
            jComboBox3.addItem("16");
            jComboBox3.addItem("17");
            jComboBox3.addItem("18");
            jComboBox3.addItem("19");
            jComboBox3.addItem("20");
            jComboBox3.addItem("21");
            jComboBox3.addItem("22");
            jComboBox3.addItem("23");
            jComboBox3.addItem("24");
            jComboBox3.addItem("25");
            jComboBox3.addItem("26");
            jComboBox3.addItem("27");
            jComboBox3.addItem("28");
            jComboBox3.addItem("29");
            jComboBox3.addItem("30");
            jComboBox3.setSelectedItem("1");
        } else if (jComboBox2.getSelectedItem().equals("2") && (jComboBox1.getSelectedItem().equals("2000")
                || jComboBox1.getSelectedItem().equals("2004")
                || jComboBox1.getSelectedItem().equals("2008")
                || jComboBox1.getSelectedItem().equals("2012")
                || jComboBox1.getSelectedItem().equals("2016")
                || jComboBox1.getSelectedItem().equals("2020"))) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("1");
            jComboBox3.addItem("2");
            jComboBox3.addItem("3");
            jComboBox3.addItem("4");
            jComboBox3.addItem("5");
            jComboBox3.addItem("6");
            jComboBox3.addItem("7");
            jComboBox3.addItem("8");
            jComboBox3.addItem("9");
            jComboBox3.addItem("10");
            jComboBox3.addItem("11");
            jComboBox3.addItem("12");
            jComboBox3.addItem("13");
            jComboBox3.addItem("14");
            jComboBox3.addItem("15");
            jComboBox3.addItem("16");
            jComboBox3.addItem("17");
            jComboBox3.addItem("18");
            jComboBox3.addItem("19");
            jComboBox3.addItem("20");
            jComboBox3.addItem("21");
            jComboBox3.addItem("22");
            jComboBox3.addItem("23");
            jComboBox3.addItem("24");
            jComboBox3.addItem("25");
            jComboBox3.addItem("26");
            jComboBox3.addItem("27");
            jComboBox3.addItem("28");
            jComboBox3.addItem("29");
            jComboBox3.setSelectedItem("1");
        } else if (jComboBox2.getSelectedItem().equals("2")) {
            jComboBox3.removeAllItems();
            jComboBox3.addItem("1");
            jComboBox3.addItem("2");
            jComboBox3.addItem("3");
            jComboBox3.addItem("4");
            jComboBox3.addItem("5");
            jComboBox3.addItem("6");
            jComboBox3.addItem("7");
            jComboBox3.addItem("8");
            jComboBox3.addItem("9");
            jComboBox3.addItem("10");
            jComboBox3.addItem("11");
            jComboBox3.addItem("12");
            jComboBox3.addItem("13");
            jComboBox3.addItem("14");
            jComboBox3.addItem("15");
            jComboBox3.addItem("16");
            jComboBox3.addItem("17");
            jComboBox3.addItem("18");
            jComboBox3.addItem("19");
            jComboBox3.addItem("20");
            jComboBox3.addItem("21");
            jComboBox3.addItem("22");
            jComboBox3.addItem("23");
            jComboBox3.addItem("24");
            jComboBox3.addItem("25");
            jComboBox3.addItem("26");
            jComboBox3.addItem("27");
            jComboBox3.addItem("28");
            jComboBox3.setSelectedItem("1");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        dispose();
        new userActivity(u_username).show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
        int row = jTable2.getSelectedRow();
        v = tm.getValueAt(row, 0).toString();
        f = tm.getValueAt(row, 3).toString();
        p = tm.getValueAt(row, 4).toString();
        r = Float.parseFloat(tm.getValueAt(row, 2).toString()) - Float.parseFloat(tm.getValueAt(row, 1).toString());
        jLabelV.setText(v);
        jLabelF.setText(f);
        jLabelR.setText("");
        jLabelTC.setText("");
        jAmount.setText("");
        jAmount.setEnabled(false);
        try {
            DefaultTableModel tm1 = (DefaultTableModel) jTable4.getModel();
            tm1.setRowCount(0);
            rs = st.executeQuery("select * from refill where f_name='" + f + "' and f_amount<=" + r);
            while (rs.next()) {
                String data[] = {String.valueOf(rs.getInt("rf_id")), rs.getString("f_name"), Float.toString(rs.getFloat("f_amount"))};

                tm1.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        jAmount.setEnabled(true);
        DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
        int row = jTable4.getSelectedRow();
        jLabelR.setText(tm.getValueAt(row, 0).toString());
        fa=Float.parseFloat(tm.getValueAt(row, 2).toString());
        jAmount.setText("0");
        jLabelTC.setText("0");

    }//GEN-LAST:event_jTable4MouseClicked

    private void jAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmountActionPerformed
        // TODO add your handling code here:
        if(jAmount.getText().toString().equals(null))
        {
            jLabelTC.setText(String.valueOf("0"));
        } else{
            price = Float.parseFloat(p) * fa * Float.parseFloat(jAmount.getText().toString());
            jLabelTC.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new request().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JTextField jHour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCost;
    private javax.swing.JLabel jLabelF;
    private javax.swing.JLabel jLabelMon;
    private javax.swing.JLabel jLabelR;
    private javax.swing.JLabel jLabelTC;
    private javax.swing.JLabel jLabelV;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JTextField jMinute;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jSecond;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
