/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project3_1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class User_approvals extends javax.swing.JFrame {

    public Connection con;
    ResultSet rs = null;
    Statement st;
    String m_username = "m";

    public User_approvals() {
        initComponents();
        setSize(1000,500);
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            st = con.createStatement();
            rs = st.executeQuery("select * from manager where m_username='" + m_username + "'");
            if (rs.next()) {
                jLabel1.setText("Welcome " + rs.getString("m_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        alldata();
    }

    public User_approvals(String x) {
        initComponents();
        m_username = x;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=projectdb1;selectMethod=cursor", "sa", "123456");
            st = con.createStatement();
            rs = st.executeQuery("select * from manager where m_username='" + m_username + "'");
            if (rs.next()) {
                jLabel1.setText("Welcome " + rs.getString("m_name"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        alldata();
    }

    public void alldata() {
        try {
            rs = st.executeQuery("select * from user_info");
            while (rs.next()) {
                String data[] = {rs.getString("u_username"), rs.getString("u_password"), rs.getString("u_approved")};
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void unApproveddata() {
        try {
            rs = st.executeQuery("select * from user_info where u_approved='no'");
            while (rs.next()) {
                String data[] = {rs.getString("u_username"), rs.getString("u_password"), rs.getString("u_approved")};
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Approveddata() {
        try {
            rs = st.executeQuery("select * from user_info where u_approved='yes'");
            while (rs.next()) {
                String data[] = {rs.getString("u_username"), rs.getString("u_password"), rs.getString("u_approved")};
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                tm.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "u_username", "u_password", "u_approved"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 110, 506, 233);

        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 370, 178, 35);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "all", "approved", "not approved" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(492, 16, 136, 31);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("m_username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 140, 40);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 370, 148, 35);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/photo-1605282003441-a966bb348137.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectionModel().isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "No row selected", "error", JOptionPane.INFORMATION_MESSAGE);
        } else {;
            try {
                DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
                int row = jTable1.getSelectedRow();
                String u_username = tm.getValueAt(row, 0).toString();

                if (tm.getValueAt(row, 2).toString().equals("no")) {
                    if (st.executeUpdate("insert into approves values('" + m_username + "','" + u_username + "')") == 1) {
                        JOptionPane.showMessageDialog(null, "Approved", "success", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                if (st.executeUpdate("UPDATE user_info set u_approved='yes' where u_username='" + u_username + "'") == 1) {
                    tm.setRowCount(0);
                    if (jComboBox1.getSelectedIndex() == 0) {
                        alldata();
                        JOptionPane.showMessageDialog(null, "Updated", "success", JOptionPane.INFORMATION_MESSAGE);
                    } else if (jComboBox1.getSelectedIndex() == 2) {
                        unApproveddata();
                        JOptionPane.showMessageDialog(null, "Updated", "success", JOptionPane.INFORMATION_MESSAGE);
                    } else if (jComboBox1.getSelectedIndex() == 1) {
                        Approveddata();
                        JOptionPane.showMessageDialog(null, "Updated", "success", JOptionPane.INFORMATION_MESSAGE);
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here;
        try {
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.setRowCount(0);
            if (jComboBox1.getSelectedIndex() == 0) {
                alldata();
            } else if (jComboBox1.getSelectedIndex() == 2) {
                unApproveddata();
            } else if (jComboBox1.getSelectedIndex() == 1) {
                Approveddata();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        managerActivity ma = new managerActivity(m_username);
        ma.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_approvals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_approvals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_approvals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_approvals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_approvals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
